### PR TITLE
Rails 4 upgrade

### PR DESCRIPTION
**Pull request by tboerger**
Just some fixes that are included for the rails 4 update at https://github.com/crowbar/barclamp-crowbar/pull/1157 for getting feedback.

### CODE REVIEW

**Comment by tboerger** [comment]
This merge is missing :)

**Comment by vuntz** [comment]
> This merge is missing :)

Because I'm unsure if all the changes are good as mentioned in previous comments. And nobody else reviewed this, so...

**Comment by tboerger** [comment]
Maybe nobody else monitors this repo as we are currently not shipping that :(

**Comment by dirkmueller** [comment]
I still think the monster "cleanup commit" should be splitted into a different PR as it needs to be closer reviewed...

**Comment by tboerger** [comment]
Somebody else can migrate that.

**Pull request closed without merging**
